[passenger]
web_doc_root = "/n/fs/myproject/mywebsitefiles/www-docroot"
user = "mynetid"
group = "projectgroup"
passenger_app_root = "/n/fs/myproject/mywebsitefiles/www-approot"
passenger_restart_dir = "/n/fs/myproject/mywebsitefiles/www-approot/tmp"
passenger_python = "/n/fs/myproject/mywebsitefiles/venv/bin/python"
[wsgi]
chdir = "/n/fs/myproject/mywebsitefiles/myapp/file1"
app = "app.app"
[secret_files]
[environment]
LOG_FILENAME = "/n/fs/myproject/mywebsitefiles/log/logfile"
